version: '3.5'

services:
  db:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chattydb
      MYSQL_USER: chattyuser
      MYSQL_PASSWORD: chattypassword
    restart: always
    container_name: "chatty_db_1"
  nest:
    build: ./chatty_backend/
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    restart: always
    container_name: "chatty_nest_1"
  angular:
    build: ./chatty_frontend/
    depends_on:
      - "nest"
    ports:
      - "15001:80"
    container_name: "chatty_angular_1"
networks:
  default:
    name: chatty_default
